import type { Metadata } from "next";
import "./globals.css";
import "nes.css/css/nes.min.css";

export const metadata: Metadata = {
  title: "IrfanKS - Portfolio",
  description: "Generated by create next app",
};
import localFont from 'next/font/local'
const kongText = localFont({
  src: "./kongtext.ttf",
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        backgroundImage: "url('/bg.gif')",
        backgroundSize: "cover",
    }} className={kongText.className}>
      <div className="h-screen bg-black/30">
          {children}
      </div>
      </body>
    </html>
  );
}
